/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Gerax
 */
public class FrmIntermedio extends javax.swing.JFrame {

    /**
     * Creates new form FrmIntermedio
     */
    public FrmIntermedio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgHimno = new javax.swing.ButtonGroup();
        bgIndependencia = new javax.swing.ButtonGroup();
        bgFlor = new javax.swing.ButtonGroup();
        bgArbol = new javax.swing.ButtonGroup();
        bgAve = new javax.swing.ButtonGroup();
        jopMensaje = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        btnModificarUsuario = new javax.swing.JToggleButton();
        lblPunteo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rbHimnoMalo = new javax.swing.JRadioButton();
        rbHimnoCorrecto = new javax.swing.JRadioButton();
        rbHimnoMalo2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbIndependenciaMalo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rbIndependenciaBueno = new javax.swing.JRadioButton();
        rbIndependenciaMalo2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rbFlorMala2 = new javax.swing.JRadioButton();
        rbFlorMala = new javax.swing.JRadioButton();
        rbFlorBuena = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rbArbolCorrecto = new javax.swing.JRadioButton();
        rbArbolMalo = new javax.swing.JRadioButton();
        rbArbolMalo2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        rbAveMalo = new javax.swing.JRadioButton();
        rbAveBueno = new javax.swing.JRadioButton();
        rbAveMalo2 = new javax.swing.JRadioButton();
        btnVerificar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblUsuario.setText("Usuario");

        btnModificarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        btnModificarUsuario.setText("Modificar Usuario");

        lblPunteo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPunteo.setText("Punteo: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addGap(81, 81, 81)
                .addComponent(lblPunteo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPunteo))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Para el siguiente nivel alcanza 65 puntos");

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setForeground(new java.awt.Color(153, 0, 51));
        btnSalir.setText("Salir");

        jLabel2.setText("En que año fue compuesto el himno nacional");

        rbHimnoMalo.setText("1800");

        rbHimnoCorrecto.setText("1897");

        rbHimnoMalo2.setText("1823");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Preguntas Guatemaltecas");

        rbIndependenciaMalo.setText("4 jul 1776");

        jLabel4.setText("En que fecha fue firmada el acto de independencia ");

        rbIndependenciaBueno.setText("15 sep 1821");

        rbIndependenciaMalo2.setText("17 enero 1921");

        jLabel5.setText("Cual es la flor nacional de Guatemala");

        rbFlorMala2.setText("Flor blanca");

        rbFlorMala.setText("Nieve Blanca");

        rbFlorBuena.setText("Monja Blanca");

        jLabel6.setText("Arbol Nacional de Guatemala");

        rbArbolCorrecto.setText("Ceiba");

        rbArbolMalo.setText("Cedro");

        rbArbolMalo2.setText("Manzanote");

        jLabel7.setText("Ave nacional de Guatemala");

        rbAveMalo.setText("Ronrones");

        rbAveBueno.setText("Quetzal");

        rbAveMalo2.setText("Zanate");

        btnVerificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cheque.png"))); // NOI18N
        btnVerificar.setText("Verificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbHimnoCorrecto)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbHimnoMalo)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbHimnoMalo2))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(rbFlorMala2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbFlorMala)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbFlorBuena)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbIndependenciaMalo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbIndependenciaBueno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbIndependenciaMalo2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(rbArbolCorrecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbArbolMalo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbArbolMalo2)))
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(185, 185, 185))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(264, 264, 264))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rbAveMalo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVerificar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbAveBueno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbAveMalo2)))
                        .addGap(233, 233, 233))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbHimnoCorrecto)
                    .addComponent(rbHimnoMalo)
                    .addComponent(rbHimnoMalo2)
                    .addComponent(rbIndependenciaMalo)
                    .addComponent(rbIndependenciaBueno)
                    .addComponent(rbIndependenciaMalo2))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFlorMala2)
                    .addComponent(rbFlorMala)
                    .addComponent(rbFlorBuena)
                    .addComponent(rbArbolCorrecto)
                    .addComponent(rbArbolMalo)
                    .addComponent(rbArbolMalo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAveMalo)
                    .addComponent(rbAveBueno)
                    .addComponent(rbAveMalo2))
                .addGap(18, 18, 18)
                .addComponent(btnVerificar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmIntermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmIntermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmIntermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmIntermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmIntermedio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup bgArbol;
    public javax.swing.ButtonGroup bgAve;
    public javax.swing.ButtonGroup bgFlor;
    public javax.swing.ButtonGroup bgHimno;
    public javax.swing.ButtonGroup bgIndependencia;
    public javax.swing.JToggleButton btnModificarUsuario;
    public javax.swing.JButton btnSalir;
    public javax.swing.JToggleButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JOptionPane jopMensaje;
    public javax.swing.JLabel lblPunteo;
    public javax.swing.JLabel lblUsuario;
    public javax.swing.JRadioButton rbArbolCorrecto;
    public javax.swing.JRadioButton rbArbolMalo;
    public javax.swing.JRadioButton rbArbolMalo2;
    public javax.swing.JRadioButton rbAveBueno;
    public javax.swing.JRadioButton rbAveMalo;
    public javax.swing.JRadioButton rbAveMalo2;
    public javax.swing.JRadioButton rbFlorBuena;
    public javax.swing.JRadioButton rbFlorMala;
    public javax.swing.JRadioButton rbFlorMala2;
    public javax.swing.JRadioButton rbHimnoCorrecto;
    public javax.swing.JRadioButton rbHimnoMalo;
    public javax.swing.JRadioButton rbHimnoMalo2;
    public javax.swing.JRadioButton rbIndependenciaBueno;
    public javax.swing.JRadioButton rbIndependenciaMalo;
    public javax.swing.JRadioButton rbIndependenciaMalo2;
    // End of variables declaration//GEN-END:variables
}
